apiVersion: v1
kind: Pod
metadata:
  name: snow-classifier
spec:
  containers:
  - name: snow-classifier
    image: us.icr.io/mfs_ibm_docker_space/snow_classifier:v4
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: icr
