apiVersion: apps/v1
kind: Deployment
metadata:
  name: snow-classifier
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snow-classifier
  template:
    metadata:
      labels:
        app: snow-classifier
    spec:
      containers:
      - name: snow-classifier
        image: us.icr.io/mfs_ibm_docker_space/snow_classifier:v4
        ports:
        - containerPort: 80
